services:
  addon:
    build: .
    environment:
      PORT: 8080
      ADDON_VERSION: 0.4.0
      QOBUZ_APP_ID: 798273057
      QOBUZ_COUNTRY_CODE: US
      QOBUZ_SESSION_FILE: /data/qobuz-session.json
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
